FROM solr:9.8.1

# Set your custom Solr home
ENV SOLR_HOME=/data

COPY --chown=0:0 scripts /opt/docker-solr/scripts
<% @tables.each do |table| %>
COPY --chown=0:0 <%= table %> /var/solr/data/<%= table %>
<% end %>
    
    RUN chmod -R 0777 /var/solr/data
    RUN chmod -R +x /opt/docker-solr/scripts
    
VOLUME /var/solr
EXPOSE 8983
WORKDIR /opt/solr
USER $SOLR_UID

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["solr-foreground"]
