name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types:
      - trigger-solr-automation-workflow

jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log event payload
      run: echo '${{ toJson(github.event.client_payload) }}'

    - name: Save event payload to file
      run: echo '${{ toJson(github.event.client_payload) }}' > file.json

    - name: Check if file.json exists and has content
      run: |
        if [ -s file.json ]; then
          echo "file.json exists and has content."
        else
          echo "file.json does not exist or is empty."
          exit 1
        fi

    - name: Print the location and contents of file.json
      run: |
        echo "Location of file.json: $(pwd)/file.json"
        echo "Contents of file.json:"
        cat file.json


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t my-chef-solo-image .

    - name: Run Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}/file.json:/var/chef/cookbooks/graphql/file.json \
        -e GITHUB_TOKEN=${{ secrets.OTHER_REPO_GITHUB_TOKEN }} \
        my-chef-solo-image

    - name: Tag Docker image
      run: |
        docker tag my-chef-solo-image:latest ${{ secrets.DOCKER_USERNAME }}/my-chef-solo-image:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-chef-solo-image:latest
